# Generated by Django 2.0.5 on 2018-05-13 05:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoSampa_BusStops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('mpoint', django.contrib.gis.db.models.fields.PointField(srid=29183)),
            ],
        ),
    ]
