# Generated by Django 2.0.5 on 2018-05-13 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geosampa_busstops',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='geosampa_busstops',
            name='lon',
        ),
    ]
