# Generated by Django 2.0.6 on 2018-11-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_website', '0004_auto_20181001_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='sessionName',
            field=models.CharField(default='defaultName', max_length=256),
            preserve_default=False,
        ),
    ]
