# Generated by Django 2.0.6 on 2018-11-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_website', '0005_session_sessionname'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterresult',
            name='density',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filterresult',
            name='presence',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geoimage',
            name='parametersJSON',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='uimodelJSON',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
