# Generated by Django 2.0.6 on 2018-12-09 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_website', '0006_auto_20181117_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='sessionName',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
