# Generated by Django 2.0.6 on 2019-01-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_website', '0007_auto_20181208_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='sessionName',
            field=models.CharField(max_length=256),
        ),
    ]
