version: '2'

services:
  db:
    image: kartoza/postgis:9.6-2.4
    expose:
      - "5432"
    ports:
      - "5432:5432/tcp"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=1234
      - POSTGRES_DBNAME=INACITYdb
  web:
    build: .
    #entrypoint: ./wait-for-postgres.sh db
    environment:
      - POSTGRES_PASS=1234
    command: bash -c "./wait-for-postgres.sh db && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    #command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    #command: bash -c "while !</dev/tcp/db/5432; do sleep 1; done; && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    expose:
      - "8000"
    ports:
      - "8000:8000/tcp"
    depends_on:
      - db        