version: '2'

services:
  db:
    image: kartoza/postgis:9.6-2.4
    volumes:
      - /var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "25432:5432/tcp"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=1234
      - POSTGRES_DBNAME=INACITYdb
