version: '2'

services:
  db:
    image: kartoza/postgis:9.6-2.4
    expose:
      - "5432"
    ports:
      - "25432:5432/tcp"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=1234
      - POSTGRES_DBNAME=INACITYdb
  inacity:
    #image: inacity
    build: .
    environment:
      - POSTGRES_PASS=1234
    #APACHE WEB SERVER
    command: bash -c "./wait-for-postgres.sh db && python3 manage.py migrate"
    #command: bash -c "touch ./anything && tail -f ./anything"
    #command: bash -c "echo 'deb http://ftp.de.debian.org/debian testing main' >> /etc/apt/sources.list"
    #command: bash -c "echo 'APT::Default-Release "stable";' | tee -a /etc/apt/apt.conf.d/00local"
    
    #command: bash -c "apt-get update"
    #command: bash -c "apt-get -t testing install -y python3.6-dev"
    #command: bash -c "a2enmod wsgi_express"
    #command: bash -c ""
    #command: bash -c ""
    command: bash -c "apache2ctl -D FOREGROUND"
    
    #DJANGO WEB SERVER
    #command: bash -c "./wait-for-postgres.sh db && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    
    
    expose:
      - "8000"
      - "80"
    ports:
      - "8000:8000/tcp"
      - "80:80/tcp"
    depends_on:
      - db
    
