version: '2'

services:
  db:
    image: kartoza/postgis:9.6-2.4
    expose:
      - "5432"
    ports:
      - "25432:5432/tcp"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=1234
      - POSTGRES_DBNAME=INACITYdb
  inacity:
    #image: inacity
    build: .
    environment:
      - POSTGRES_PASS=1234
    #APACHE WEB SERVER
    command: >
        sh -c "./wait-for-postgres.sh db
        && python3 manage.py migrate
        && apache2ctl -D FOREGROUND"

    expose:
      - "8000"
      - "80"
    ports:
      - "8000:8000/tcp"
      - "80:80/tcp"
    depends_on:
      - db
    
