version: '2'

services:
  rediscache:
    image: redis:5.0.6
    expose:
      - "6379"
    ports:
      - "6379:6379/tcp"
  graphdb:
    image: neo4j
    volumes:
      - /var/lib/neo4j/data
    expose:
      - "7474"
      - "7687"
    ports:
      - "7474:7474/tcp"
      - "7687:7687/tcp"
  db:
    image: kartoza/postgis:9.6-2.4
    volumes:
      - /var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "25432:5432/tcp"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=1234
      - POSTGRES_DBNAME=INACITYdb
  inacity:
    image: inacity
    volumes:
      - ./:/var/www/html/
    build: .
    environment:
      - POSTGRES_PASS=1234
      - POSTGRES_USER=postgres
      - NEO4J_PASS=1234
      - NEO4J_USER=neo4j
    working_dir: /var/www/html/

    command: >
        sh -c "cd /var/www/html/
        && chmod +x /var/www/html/install_script.sh 
        && bash /var/www/html/install_script.sh
        && chmod +x /var/www/html/wait-for-postgres.sh
        && bash /var/www/html/wait-for-postgres.sh db
        && python3 manage.py makemigrations
        && python3 manage.py migrate
        && python3 manage.py collectstatic --noinput
        && python3 manage.py collectstatic_js_reverse
        && echo 'from django_website import load; load.run(False)' | python manage.py shell
        && nohup daphne -b 0.0.0.0 -p 8000 django_website.asgi:application > /dev/null &
        && apache2ctl -D FOREGROUND
        && tail -f /dev/null"
        

    expose:
      - "3000"
      - "8000"
      - "80"
    ports:
      - "3000:3000/tcp"
      - "8000:8000/tcp"
      - "80:80/tcp"
    depends_on:
      - db
    tty: true
